### ISSUE TITLE
[1.15.2] Required Dependency on Curseforge

### ISSUE THREAD

**Issue by realTIMematrix** [WTBW-Mods/WTBW_Core#1]
The other WTBW Modules requires the Core Module and/or Library...

But the Core Module requires the Core Module? Sounds like a WTBW Core Inception with Leonardo di Corepio ;-)

And the WTBW Library requires not the Core Module? Did I miss something :-)

Think this can easy be fixed on curseforge :-)

**Comment by Sunekaer** [comment]
Fixed :)
Core dep on Lib
Tools, Machines and deco dep on Lib and Core
